apiVersion: apps/v1
kind: Deployment
metadata:
  name: jshelper
  labels:
    app: jshelper
spec:
  replicas: "{{$.iios.app.replicas}}"
  selector:
    matchLabels:
      app: jshelper
  template:
    metadata:
      labels:
        app: jshelper
    spec:
      containers:
      - name: jshelper
        image: "ignitial/jshelper:{{$.iios.app.version}}"
        imagePullPolicy: "{{$.iios.app.imagePullPolicy}}"
        volumeMounts:
        - name: config-volume
          mountPath: /opt/jshelper/server/config/generated
        ports: "{{$.iios.app.ports}}"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-volume
          configMap:
            name: jshelper-config

---
apiVersion: v1
kind: Service
metadata:
  name: jshelper
spec:
  selector:
    app: jshelper
  ports:
  - name: http
    port: "{{$.iios.app.ports[0].containerPort}}"
    targetPort: "{{$.iios.app.ports[0].containerPort}}"
